version: '3.8'
services:
  reservationservice:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: reservation_db
    ports:
      - "3306:3306"